[Database]
; Pilihan driver: QSQLITE, QMYSQL, QPSQL
Driver=QSQLITE
Path=/usr/lib/cgi-bin/azzammar/data/azzammar.db

; Jika ingin diubah ke DB Server lain, aktifkan baris di bawah ini:
; Driver=QMYSQL
; Host=192.168.1.5
; Name=azzammar_prod
; User=admin_azzammar
; Password=securepassword123
; Port=3306

