# Empty targets configuration file -- please see the package
# documentation directory for an example.
#
# You can drop individual config snippets into /etc/tgt/conf.d
#include /etc/tgt/conf.d/*.conf
default-driver iscsi

<target iqn.2026-09.server:windows-os>
    initiator-address ALL
    backing-store /var/diskless/images/windows_base.img
    controller_tid 1
    lun 1 
    write-cache on
    block-size 512
</target>
<target iqn.2026-09.server:gamedisk>
    initiator-address ALL
    backing-store /mnt/games/games_master.img
    controller_tid 2
    lun 1
    readonly 1
    write-cache on
    block-size 512
</target>
